version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
      - name: customers

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        freshness:
          warn_after: {count: 3, period: minute}
        loaded_at_field: _BATCHED_AT
          

